version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi
    environment:
      - PORT=8000
    volumes:
      - .:/app
    expose:
      - "8000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - fastapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
